//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.34014
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace strillone.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("strillone.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a aggiungi.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Voce di menu.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a APPLICAZIONE.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edizione del.
        /// </summary>
        public static string EditionStamp {
            get {
                return ResourceManager.GetString("EditionStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sei entrato nella sezione.
        /// </summary>
        public static string EnterSezione {
            get {
                return ResourceManager.GetString("EnterSezione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore di connessione con il server.
        /// </summary>
        public static string ErrorServer {
            get {
                return ResourceManager.GetString("ErrorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chiusura applicazione.
        /// </summary>
        public static string ExitApp {
            get {
                return ResourceManager.GetString("ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Strillone è un&apos;applicazione di Informatici senza Frontiere che consente di ascoltare le notizie sullo smartphone del proprio giornale preferito mediante la sintesi vocale integrata. Utilizzare Strillone è facile e veloce, tenendo il tuo telefono o tablet tra le mani, identifica i quattro angoli dello schermo, ad ognuno di essi è associata un&apos;azione. Angolo superiore sinistro: Tocca brevemente questo angolo per tornare al livello superiore. Se, ad esempio, stai navigando gli articoli, premendo questo angolo  [stringa troncata]&quot;;.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Caricamento dati....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gennaio.
        /// </summary>
        public static string Mese1 {
            get {
                return ResourceManager.GetString("Mese1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ottobre.
        /// </summary>
        public static string Mese10 {
            get {
                return ResourceManager.GetString("Mese10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Novembre.
        /// </summary>
        public static string Mese11 {
            get {
                return ResourceManager.GetString("Mese11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dicembre.
        /// </summary>
        public static string Mese12 {
            get {
                return ResourceManager.GetString("Mese12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Febbraio.
        /// </summary>
        public static string Mese2 {
            get {
                return ResourceManager.GetString("Mese2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Marzo.
        /// </summary>
        public static string Mese3 {
            get {
                return ResourceManager.GetString("Mese3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aprile.
        /// </summary>
        public static string Mese4 {
            get {
                return ResourceManager.GetString("Mese4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Maggio.
        /// </summary>
        public static string Mese5 {
            get {
                return ResourceManager.GetString("Mese5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Giugno.
        /// </summary>
        public static string Mese6 {
            get {
                return ResourceManager.GetString("Mese6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Luglio.
        /// </summary>
        public static string Mese7 {
            get {
                return ResourceManager.GetString("Mese7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Agosto.
        /// </summary>
        public static string Mese8 {
            get {
                return ResourceManager.GetString("Mese8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settembre.
        /// </summary>
        public static string Mese9 {
            get {
                return ResourceManager.GetString("Mese9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non è stata selezionato alcuna articolo.
        /// </summary>
        public static string NoNodeSelectedArticolo {
            get {
                return ResourceManager.GetString("NoNodeSelectedArticolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non è stata selezionata alcuna sezione.
        /// </summary>
        public static string NoNodeSelectedSezione {
            get {
                return ResourceManager.GetString("NoNodeSelectedSezione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non è stata selezionata alcuna testata.
        /// </summary>
        public static string NoNodeSelectedTestata {
            get {
                return ResourceManager.GetString("NoNodeSelectedTestata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non ci sono testate nella tua lingua.
        /// </summary>
        public static string noTitles {
            get {
                return ResourceManager.GetString("noTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a it-it.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Navigazione edizioni.
        /// </summary>
        public static string StartEdizioni {
            get {
                return ResourceManager.GetString("StartEdizioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inizio navigazione.
        /// </summary>
        public static string StartNavigazione {
            get {
                return ResourceManager.GetString("StartNavigazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Navigazione sezioni.
        /// </summary>
        public static string StartSezioni {
            get {
                return ResourceManager.GetString("StartSezioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Entra.
        /// </summary>
        public static string SuggestionBtnEntra {
            get {
                return ResourceManager.GetString("SuggestionBtnEntra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Precedente.
        /// </summary>
        public static string SuggestionBtnPrecedente {
            get {
                return ResourceManager.GetString("SuggestionBtnPrecedente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sali.
        /// </summary>
        public static string SuggestionBtnSali {
            get {
                return ResourceManager.GetString("SuggestionBtnSali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Successivo.
        /// </summary>
        public static string SuggestionBtnSuccessivo {
            get {
                return ResourceManager.GetString("SuggestionBtnSuccessivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Usa il pulsante in basso a destra per scorrere gli articoli.
        /// </summary>
        public static string SuggestionOnArticle {
            get {
                return ResourceManager.GetString("SuggestionOnArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sei al primo articolo.
        /// </summary>
        public static string SuggestionOnPositionArticolo {
            get {
                return ResourceManager.GetString("SuggestionOnPositionArticolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sei all&apos;ultimo articolo.
        /// </summary>
        public static string SuggestionOnPositionLastArticolo {
            get {
                return ResourceManager.GetString("SuggestionOnPositionLastArticolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sei all&apos;ultima sezione.
        /// </summary>
        public static string SuggestionOnPositionLastSezione {
            get {
                return ResourceManager.GetString("SuggestionOnPositionLastSezione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sei all&apos;ultima testata.
        /// </summary>
        public static string SuggestionOnPositionLastTestata {
            get {
                return ResourceManager.GetString("SuggestionOnPositionLastTestata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sei alla prima sezione.
        /// </summary>
        public static string SuggestionOnPositionSezione {
            get {
                return ResourceManager.GetString("SuggestionOnPositionSezione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sei alla prima testata.
        /// </summary>
        public static string SuggestionOnPositionTestata {
            get {
                return ResourceManager.GetString("SuggestionOnPositionTestata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Usa il pulsante in basso a destra per scorrere le sezioni.
        /// </summary>
        public static string SuggestionOnSection {
            get {
                return ResourceManager.GetString("SuggestionOnSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Usa il pulsante in basso a destra per scorrere le testate.
        /// </summary>
        public static string SuggestionOnTitle {
            get {
                return ResourceManager.GetString("SuggestionOnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pronta per la lettura.
        /// </summary>
        public static string TestataReady {
            get {
                return ResourceManager.GetString("TestataReady", resourceCulture);
            }
        }
    }
}
